"""Criacao das tabelas

Revision ID: 6dc9020dec51
Revises: 
Create Date: 2026-09-01 16:01:02.352747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc9020dec51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('musics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('album_img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_uri', sa.String(), nullable=False),
    sa.Column('ms_played', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('offline', sa.Boolean(), nullable=False),
    sa.Column('offline_ts', sa.BigInteger(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('source_file_row', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='in_queue', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_ref', sa.String(), nullable=False),
    sa.Column('ms_played', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offline', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['music_ref'], ['musics.reference'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_artist_association',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ),
    sa.PrimaryKeyConstraint('music_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_artist_association')
    op.drop_table('executions')
    op.drop_table('queue')
    op.drop_table('musics')
    op.drop_table('artists')
    # ### end Alembic commands ###
