"""Recriando tabelas

Revision ID: da2960286730
Revises: 
Create Date: 2026-09-05 04:57:20.674209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2960286730'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('musics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('names', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('album_img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('music_artist_association',
    sa.Column('music_reference', sa.String(), nullable=False),
    sa.Column('artist_reference', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_reference'], ['artists.reference'], ),
    sa.ForeignKeyConstraint(['music_reference'], ['musics.reference'], ),
    sa.PrimaryKeyConstraint('music_reference', 'artist_reference')
    )
    op.create_foreign_key(None, 'executions', 'musics', ['music_reference'], ['reference'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_table('music_artist_association')
    op.drop_table('musics')
    op.drop_table('artists')
    # ### end Alembic commands ###
